#!/usr/bin/env bash
# SPDX-License-Identifier: MPL-2.0
# check-tg3-differential.sh — verify the TG-3 translation-validation obligations.
#
# proofs/TG3Differential.lean is generated by compiler/test/tg3/tg3_emit.ml: one
# `infer [] <term> = <result> := by decide` obligation per core-fragment term,
# where <result> is what OCaml `infer_expr` computed.  Lean's *proven* `infer`
# (TG-2: infer ≡ HasType) kernel-checks each, so 0 errors ⟺ OCaml `infer_expr`
# refines the Lean HasType spec on the whole corpus (the machine-checked half of
# TG-3; the closure argument is in proofs/TG3-REFINEMENT.md).
#
# Unlike `lean Tangle.lean`, the differential file `import`s Tangle, so it needs
# Tangle compiled to an .olean first.  This script does both, hermetically.
#
# USAGE:  proofs/check-tg3-differential.sh        # 0 == OK
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
DIFF_FILE="$SCRIPT_DIR/TG3Differential.lean"
ORACLE="$SCRIPT_DIR/Tangle.lean"

[ -f "$DIFF_FILE" ] || { echo "::error::$DIFF_FILE missing — regenerate with tg3_emit --emit"; exit 1; }
[ -f "$ORACLE" ]    || { echo "::error::$ORACLE missing"; exit 1; }

# Put Lean on PATH (pinned toolchain; GitHub-asset fallback).
eval "$("$SCRIPT_DIR/bootstrap-lean.sh" --print-path)"

BUILD_DIR="$(mktemp -d)"
trap 'rm -rf "$BUILD_DIR"' EXIT

echo "TG-3: compiling Tangle.lean → olean (oracle for import)…"
( cd "$SCRIPT_DIR" && lean -o "$BUILD_DIR/Tangle.olean" Tangle.lean )

echo "TG-3: kernel-checking $(grep -c 'example :' "$DIFF_FILE") obligations in TG3Differential.lean…"
out="$BUILD_DIR/out.txt"
( cd "$SCRIPT_DIR" && LEAN_PATH="$BUILD_DIR" lean TG3Differential.lean ) 2>&1 | tee "$out" || true

errors=$(grep -c "error:" "$out" || true)
if [ "$errors" -ne 0 ]; then
  echo "::error::TG3Differential.lean has $errors error(s) — OCaml infer_expr disagrees with Lean infer."
  exit 1
fi
echo "TG-3: TG3Differential.lean — 0 errors. OCaml infer_expr ≡ Lean infer on the corpus. GREEN."
